- hosts: jenkins-slave
  become: true
  tasks:
    - name: Update the Ubantu repo
      apt:
        update_cache: true
        cache_valid_time: 3600
    - name: Install Java needed for slave
      apt:
        name: openjdk-11-jre
        state: present
    - nmae: Download Maven Package
      get_url:
        url: https://dlcdn.apache.org/maven/maven-3/3.8.8/binaries/apache-maven-3.8.8-bin.tar.gz
        dest: /opt/
    - name: Extracting Maven Package
      unarchive:
        src: /opt/apache-maven-3.8.8-bin.tar.gz
        dest: /opt/
        remote_src: yes
    - name: Download the jave
      get_url:
        url: https://download.java.net/java/GA/jdk17.0.2/dfd4a8d0985749f896bed50d7138ee7f/8/GPL/openjdk-17.0.2_linux-x64_bin.tar.gz
        dest: /opt/
    - name: Extracting Jave packages
      unarchive:
        src: /opt/openjdk-17.0.2_linux-x64_bin.tar.gz
        dest: /opt/
        remote_src: yes 
    - name: Move to jdk-17
      command: mv /opt/jdk-17.0.2/ /opt/jdk-17/      
